### ISSUE TITLE
What are veth-init and veth-vpn?

### ISSUE THREAD

**Issue by gimmelemons** [chrisbouchard/namespaced-wireguard-vpn#2]
Hi @chrisbouchard ,

Thanks for this project, I've been looking to do similar thing.

I am using wireguard, I have an assigned ip, private key, public key etc, and the machine is connected to internet using wireless(wlpxx). But I am not sure what to fill the following with -

> `TUNNEL_INIT_NAME:` Name to assign to the created tunnel (veth) network interface in the default (init) network namespace.
> `TUNNEL_INIT_IP_ADDRESSES:` Comma-separated list of static IP addresses to assign to the tunnel interface in the default (init) network namespace.
> `TUNNEL_VPN_NAME:` Name to assign to the created tunnel (veth) network interface in the VPN network namespace.
> `TUNNEL_VPN_IP_ADDRESSES:` Comma-separated list of static IP addresses to assign to the tunnel interface in the VPN network namespace.

Do these ip addresses need to be assigned by the router?

Edit: I think I get what those are. But why is the tunnel needed? It is not mentioned in the WG page - https://www.wireguard.com/netns/#the-new-namespace-solution either

**Comment by chrisbouchard** [comment]
Sorry I let this slip through the cracks. They are a pair of virtual ethernet devices to allow communication into the VPN namespace from the root namespace. They are not necessary in general, but I needed them for my setup. E.g., you can run Transmission in the VPN namespace, and control it via Transmission Remote over the tunnel interfaces.

Their IP addresses can just be unused static private IP addresses. I use 10.127.0.1 and 10.127.0.2, but those are meaningless private IP addresses. Whatever you set in the config will be applied by `namespaced-wireguard-vpn-tunnel.service` when it creates the interfaces.

As things are written now, they're required&nbsp;&mdash; in the sense that they are created by `namespaced-wireguard-vpn-tunnel.service` which is listed as required by `namespaced-wireguard-vpn.target`. You should be able to edit the target and remove that requires line. If the service doesn't start they will not be created, and the Wireguard part should work as usual.

**Comment by chrisbouchard** [comment]
For reference, making the tunnel optional is in the TODO list in the README.

**Comment by gimmelemons** [comment]
Thanks for explanation
