### ISSUE TITLE
IPv6 Routing support.

### ISSUE THREAD

**Issue by dsully** [chrisbouchard/namespaced-wireguard-vpn#4]
Hi - `namespaced-wireguard-vpn-interface` doesn't support setting the default route for IPv6 traffic on the Wireguard interface properly.

Would you accept a patch to change the config file to have separate v4 and v6 addresses, and 2 explicit -6 calls, such as:

```
ip -n "$NETNS_NAME" address add "$WIREGUARD_IPv4_ADDRESSES" dev "$WIREGUARD_NAME" || die
ip -n "$NETNS_NAME" -6 address add "$WIREGUARD_IPv6_ADDRESSES" dev "$WIREGUARD_NAME" || die

ip -n "$NETNS_NAME" link set "$WIREGUARD_NAME" up || die
ip -n "$NETNS_NAME" route add default dev "$WIREGUARD_NAME" || die
ip -n "$NETNS_NAME" -6 route add default dev "$WIREGUARD_NAME" || die
```

**Comment by chrisbouchard** [comment]
The part about adding an IPv6 default route sounds like a good addition, but is the `-6` necessary to add an IPv6 address to the device? As far as I can tell, `ip address` should be able to tell the version by the address format.

> <dl>
> <dt>local ADDRESS (default)</dt>
> <dd>the address of the interface. The format of the address depends on the protocol. It is a dotted quad for IP and <b>a sequence of hexadecimal halfwords separated by colons for IPv6.</b> The ADDRESS may be followed by a slash and a decimal number which encodes the network prefix length.</dd>
> </dl>
>
> &mdash; [Man page for `ip address`](https://man7.org/linux/man-pages/man8/ip-address.8.html) (Emphasis mine.)

> <dl>
> <dt>-f, -family &lt;FAMILY&gt;</dt>
> <dd>Specifies the protocol family to use. The protocol family identifier can be one of inet, inet6, bridge, mpls or link.  <b>If this option is not present, the protocol family is guessed from other arguments.</b> If the rest of the command line does not give enough information to guess the family, ip falls back to the default one, usually inet or any.</dd>
> </dl>
> &hellip;
> <dl>
> <dt>-6</dt>
> <dd>shortcut for -family inet6.</dd>
> </dl>
>
> &mdash; [Man page for `ip`](https://man7.org/linux/man-pages/man8/ip.8.html) (Emphasis mine.)

I haven't experimented much with this yet, so I'm mostly going by the documentation. I'd really rather not have to split the address list if possible.

**Comment by chrisbouchard** [comment]
@dsully When you have a moment, could you try out the change in #5 with `$WIREGUARD_IP_ADDRESSES` containing a mixed list of IPv4 and IPv6 addresses? I'm very curious if adding the route is enough to fix it.

**Comment by dsully** [comment]
Yes, that appears to work. Thanks!

**Comment by chrisbouchard** [comment]
Awesome. I have one other change I want to get in and then I'll release a new version.
